version: '3.3'

services:
    postgres:
        image: postgres:14
        restart: unless-stopped
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=12345
#        healthcheck:
#            test: ["CMD-SHELL", "pg_isready"]
#            interval: 10s
#            timeout: 5s
#            retries: 3

    go-app:
        restart: unless-stopped
        build: ./
#        depends_on:
#            db:
#                condition: service_healthy
        environment:
            APP_DSN: ${DEFAULT_DSN}
        volumes:
            - ./../:/app
        ports:
            - "8000:8000"
volumes:
    pgdata: